stages:
  anyname_model:
    cmd: python app.py
    deps:
    - app.py
    - data/hugging_face.csv
    outs:
    - spam_ham_model.pkl
    - vectorizer.pkl
  another_name:
    cmd: python app.py
    deps:
    - app.py
    - data/hugging_face.csv
    outs:
    - spam_ham_model_2.pkl
    - vectorizer_2.pkl
  another_name_1:
    cmd: python app.py
    deps:
    - app.py
    - data/hugging_face.csv
    outs:
    - spam_ham_model_3.pkl
    - vectorizer_3.pkl
